spring:
  application:
    name: gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8091
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
