spring:
  application:
    name: gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8091
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
